In [ ]:
pip install pandas numpy ipykernel openpyxl matplotlib seaborn

In [3]:
import pandas as pd

In [ ]:
products = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Products")

In [42]:
products.index

Index(['P0001', 'P0002', 'P0003', 'P0004', 'P0005', 'P0006', 'P0007', 'P0008',
       'P0009', 'P0010', 'P0011', 'P0012', 'P0013', 'P0014', 'P0015', 'P0016',
       'P0017', 'P0018', 'P0019', 'P0020', 'P0021', 'P0022', 'P0023', 'P0024',
       'P0025', 'P0026', 'P0027', 'P0028', 'P0029', 'P0030', 'P0031', 'P0032',
       'P0033', 'P0034', 'P0035', 'P0036', 'P0037', 'P0038', 'P0039', 'P0040',
       'P0041', 'P0042', 'P0043', 'P0044', 'P0045', 'P0046', 'P0047', 'P0048',
       'P0049', 'P0050', 'P0051', 'P0052', 'P0053', 'P0054', 'P0055', 'P0056',
       'P0057', 'P0058', 'P0059', 'P0060', 'P0061', 'P0062', 'P0063', 'P0064',
       'P0065', 'P0066', 'P0067', 'P0068', 'P0069', 'P0070', 'P0071', 'P0072',
       'P0073', 'P0074', 'P0075', 'P0076', 'P0077', 'P0078', 'P0079', 'P0080',
       'P0081', 'P0082', 'P0083', 'P0084', 'P0085', 'P0086', 'P0087', 'P0088',
       'P0089', 'P0090', 'P0091', 'P0092', 'P0093', 'P0094', 'P0095'],
      dtype='str', name='Product_ID')

In [38]:
products.head()

,Product_Name,Category_ID,Category,Subcategory,Brand,Unit_Cost,List_Price
Product_ID,,,,,,,
P0001,Samsung Galaxy A55,CAT001,Electronics,Smartphones,Samsung,19789,30400
P0002,OnePlus Nord CE 4,CAT001,Electronics,Smartphones,OnePlus,31755,44700
P0003,Apple iPhone 15,CAT001,Electronics,Smartphones,Apple,1084,1400
P0004,Vivo V30,CAT001,Electronics,Smartphones,Vivo,20974,28700
P0005,Nothing Phone 2a,CAT001,Electronics,Smartphones,Nothing,1046,1600

In [10]:
type(products)

pandas.DataFrame

In [11]:
products.to_csv("products.csv",index=False)

In [12]:
products.to_json("products.json",index=False)

In [13]:
df = pd.read_json("products.json")

In [14]:
df.head()

,Product_ID,Product_Name,Category_ID,Category,Subcategory,Brand,Unit_Cost,List_Price
0,P0001,Samsung Galaxy A55,CAT001,Electronics,Smartphones,Samsung,19789,30400
1,P0002,OnePlus Nord CE 4,CAT001,Electronics,Smartphones,OnePlus,31755,44700
2,P0003,Apple iPhone 15,CAT001,Electronics,Smartphones,Apple,1084,1400
3,P0004,Vivo V30,CAT001,Electronics,Smartphones,Vivo,20974,28700
4,P0005,Nothing Phone 2a,CAT001,Electronics,Smartphones,Nothing,1046,1600

In [21]:
df = pd.read_csv("products.csv",sep="$")

In [22]:
df.head()

,Product_ID,Product_Name,Category_ID,Category,Subcategory,Brand,Unit_Cost,List_Price
0,P0001,Samsung Galaxy A55,CAT001,Electronics,Smartphones,Samsung,19789,30400
1,P0002,OnePlus Nord CE 4,CAT001,Electronics,Smartphones,OnePlus,31755,44700
2,P0003,Apple iPhone 15,CAT001,Electronics,Smartphones,Apple,1084,1400
3,P0004,Vivo V30,CAT001,Electronics,Smartphones,Vivo,20974,28700
4,P0005,Nothing Phone 2a,CAT001,Electronics,Smartphones,Nothing,1046,1600

In [24]:
df.head()

,Product_ID,Product_Name,Category_ID,Category,Subcategory,Brand,Unit_Cost,List_Price
0,P0001,Samsung Galaxy A55,CAT001,Electronics,Smartphones,Samsung,19789,30400
1,P0002,OnePlus Nord CE 4,CAT001,Electronics,Smartphones,OnePlus,31755,44700
2,P0003,Apple iPhone 15,CAT001,Electronics,Smartphones,Apple,1084,1400
3,P0004,Vivo V30,CAT001,Electronics,Smartphones,Vivo,20974,28700
4,P0005,Nothing Phone 2a,CAT001,Electronics,Smartphones,Nothing,1046,1600

In [29]:
df['Category']

0          Electronics
1          Electronics
2          Electronics
3          Electronics
4          Electronics
            ...
90    Sports & Fitness
91    Sports & Fitness
92    Sports & Fitness
93    Sports & Fitness
94    Sports & Fitness
Name: Category, Length: 95, dtype: str

loc & iloc


- loc: is label based
- iloc is index based

In [46]:
df = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Products",index_col="Product_ID")

In [47]:
df.head(10)

,Product_Name,Category_ID,Category,Subcategory,Brand,Unit_Cost,List_Price
Product_ID,,,,,,,
P0001,Samsung Galaxy A55,CAT001,Electronics,Smartphones,Samsung,19789,30400
P0002,OnePlus Nord CE 4,CAT001,Electronics,Smartphones,OnePlus,31755,44700
P0003,Apple iPhone 15,CAT001,Electronics,Smartphones,Apple,1084,1400
P0004,Vivo V30,CAT001,Electronics,Smartphones,Vivo,20974,28700
P0005,Nothing Phone 2a,CAT001,Electronics,Smartphones,Nothing,1046,1600
P0006,HP Pavilion 14,CAT002,Electronics,Laptops,HP,3701,4850
P0007,Dell Inspiron 15,CAT002,Electronics,Laptops,Dell,12456,16850
P0008,Lenovo IdeaPad Slim 5,CAT002,Electronics,Laptops,Lenovo,4065,6750
P0009,ASUS Vivobook 15,CAT002,Electronics,Laptops,ASUS,6324,11200
P0010,Acer Aspire 5,CAT002,Electronics,Laptops,Acer,26977,38800

In [48]:
df.iloc[:20]

,Product_Name,Category_ID,Category,Subcategory,Brand,Unit_Cost,List_Price
Product_ID,,,,,,,
P0001,Samsung Galaxy A55,CAT001,Electronics,Smartphones,Samsung,19789,30400
P0002,OnePlus Nord CE 4,CAT001,Electronics,Smartphones,OnePlus,31755,44700
P0003,Apple iPhone 15,CAT001,Electronics,Smartphones,Apple,1084,1400
P0004,Vivo V30,CAT001,Electronics,Smartphones,Vivo,20974,28700
P0005,Nothing Phone 2a,CAT001,Electronics,Smartphones,Nothing,1046,1600
P0006,HP Pavilion 14,CAT002,Electronics,Laptops,HP,3701,4850
P0007,Dell Inspiron 15,CAT002,Electronics,Laptops,Dell,12456,16850
P0008,Lenovo IdeaPad Slim 5,CAT002,Electronics,Laptops,Lenovo,4065,6750
P0009,ASUS Vivobook 15,CAT002,Electronics,Laptops,ASUS,6324,11200
P0010,Acer Aspire 5,CAT002,Electronics,Laptops,Acer,26977,38800
P0011,Sony WH-1000XM5,CAT003,Electronics,Audio,Sony,17873,28300
P0012,JBL Tune 770NC,CAT003,Electronics,Audio,JBL,56203,74400
P0013,Boat Airdopes 141,CAT003,Electronics,Audio,Boat,18438,31000
P0014,Bose QuietComfort,CAT003,Electronics,Audio,Bose,4201,7500
P0015,JBL Flip 6,CAT003,Electronics,Audio,JBL,1273,1800
P0016,Anker USB-C Hub,CAT013,Electronics,Accessories,Anker,20549,26600
P0017,Logitech MX Master 3S,CAT013,Electronics,Accessories,Logitech,2509,3950
P0018,Samsung 256GB SSD,CAT013,Electronics,Accessories,Samsung,4511,7600
P0019,Belkin Power Bank,CAT013,Electronics,Accessories,Belkin,1088,1650
P0020,Portronics Keyboard,CAT013,Electronics,Accessories,Portronics,1795,2550

In [51]:
df.iloc[:20,5:]

            Unit_Cost  List_Price
Product_ID
P0001           19789       30400
P0002           31755       44700
P0003            1084        1400
P0004           20974       28700
P0005            1046        1600
P0006            3701        4850
P0007           12456       16850
P0008            4065        6750
P0009            6324       11200
P0010           26977       38800
P0011           17873       28300
P0012           56203       74400
P0013           18438       31000
P0014            4201        7500
P0015            1273        1800
P0016           20549       26600
P0017            2509        3950
P0018            4511        7600
P0019            1088        1650
P0020            1795        2550