In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("products.csv",sep="$")

In [3]:
df.head()

,Product_ID,Product_Name,Category_ID,Category,Subcategory,Brand,Unit_Cost,List_Price
0,P0001,Samsung Galaxy A55,CAT001,Electronics,Smartphones,Samsung,19789,30400
1,P0002,OnePlus Nord CE 4,CAT001,Electronics,Smartphones,OnePlus,31755,44700
2,P0003,Apple iPhone 15,CAT001,Electronics,Smartphones,Apple,1084,1400
3,P0004,Vivo V30,CAT001,Electronics,Smartphones,Vivo,20974,28700
4,P0005,Nothing Phone 2a,CAT001,Electronics,Smartphones,Nothing,1046,1600

## Value counts

In [60]:
df['Category'].value_counts()

Category
Electronics               20
Home Appliances           15
Furniture                 15
Fashion                   15
Beauty & Personal Care    15
Sports & Fitness          15
Name: count, dtype: int64

## Group by

In [4]:
df.groupby("Category")

In [6]:
df['Category'].value_counts()

Category
Electronics               20
Home Appliances           15
Furniture                 15
Fashion                   15
Beauty & Personal Care    15
Sports & Fitness          15
Name: count, dtype: int64

In [7]:
df.groupby("Category")['Unit_Cost'].mean()

Category
Beauty & Personal Care     1429.400000
Electronics               12830.550000
Fashion                    1349.133333
Furniture                  6277.666667
Home Appliances            7985.133333
Sports & Fitness           2493.866667
Name: Unit_Cost, dtype: float64

In [9]:
df.groupby("Category")['Unit_Cost'].min()

Category
Beauty & Personal Care     135
Electronics               1046
Fashion                    199
Furniture                  742
Home Appliances            520
Sports & Fitness           224
Name: Unit_Cost, dtype: int64

In [13]:
df.groupby("Category")['Unit_Cost'].sum()

Category
Beauty & Personal Care     21441
Electronics               256611
Fashion                    20237
Furniture                  94165
Home Appliances           119777
Sports & Fitness           37408
Name: Unit_Cost, dtype: int64

In [14]:
df.groupby("Category")['Unit_Cost'].max()

Category
Beauty & Personal Care     4990
Electronics               56203
Fashion                    5972
Furniture                 21858
Home Appliances           23780
Sports & Fitness           8310
Name: Unit_Cost, dtype: int64

In [15]:
df.groupby("Category")['Unit_Cost'].count()

Category
Beauty & Personal Care    15
Electronics               20
Fashion                   15
Furniture                 15
Home Appliances           15
Sports & Fitness          15
Name: Unit_Cost, dtype: int64

In [16]:
df.groupby("Category")['Unit_Cost'].median()

Category
Beauty & Personal Care     663.0
Electronics               5417.5
Fashion                    547.0
Furniture                 2780.0
Home Appliances           6860.0
Sports & Fitness          1090.0
Name: Unit_Cost, dtype: float64

In [17]:
df.groupby("Category")['Unit_Cost'].std()

Category
Beauty & Personal Care     1635.837522
Electronics               14130.200354
Fashion                    1677.003061
Furniture                  6852.861693
Home Appliances            6692.457992
Sports & Fitness           2887.925129
Name: Unit_Cost, dtype: float64

In [18]:
df.groupby("Category")['Unit_Cost'].var()

Category
Beauty & Personal Care    2.675964e+06
Electronics               1.996626e+08
Fashion                   2.812339e+06
Furniture                 4.696171e+07
Home Appliances           4.478899e+07
Sports & Fitness          8.340112e+06
Name: Unit_Cost, dtype: float64

#### Multiple aggregations

In [21]:
df.groupby('Category')['Unit_Cost'].agg(['mean','sum','count'])

                                mean     sum  count
Category
Beauty & Personal Care   1429.400000   21441     15
Electronics             12830.550000  256611     20
Fashion                  1349.133333   20237     15
Furniture                6277.666667   94165     15
Home Appliances          7985.133333  119777     15
Sports & Fitness         2493.866667   37408     15

#### Group multiple columns

In [25]:
df.groupby(['Category','Subcategory'])['Unit_Cost'].mean().reset_index()

                  Category        Subcategory  Unit_Cost
0   Beauty & Personal Care           Haircare     1345.0
1   Beauty & Personal Care      Personal Care     1153.8
2   Beauty & Personal Care           Skincare     1789.4
3              Electronics        Accessories     6090.4
4              Electronics              Audio    19597.6
5              Electronics            Laptops    10704.6
6              Electronics        Smartphones    14929.6
7                  Fashion        Accessories      573.8
8                  Fashion                Men     2256.4
9                  Fashion              Women     1217.2
10               Furniture            Bedroom     7085.0
11               Furniture        Living Room     9099.6
12               Furniture             Office     2648.4
13         Home Appliances           Cleaning     6379.0
14         Home Appliances            Cooling     7455.2
15         Home Appliances            Kitchen    10121.2
16        Sports & Fitness  Fitness Equipment     1778.2
17        Sports & Fitness       Fitness Wear     3645.0
18        Sports & Fitness            Outdoor     2058.4

In [26]:
df.groupby('Category')[['Unit_Cost','List_Price']].mean()

                           Unit_Cost    List_Price
Category
Beauty & Personal Care   1429.400000   2150.000000
Electronics             12830.550000  18530.000000
Fashion                  1349.133333   1936.666667
Furniture                6277.666667   9920.000000
Home Appliances          7985.133333  11756.666667
Sports & Fitness         2493.866667   3536.666667

In [29]:
df.groupby('Category').agg(
   { "Unit_Cost":'sum',
    "List_Price":"mean",
    "List_Price":"sum"}
)

                        Unit_Cost  List_Price
Category
Beauty & Personal Care      21441       32250
Electronics                256611      370600
Fashion                     20237       29050
Furniture                   94165      148800
Home Appliances            119777      176350
Sports & Fitness            37408       53050

In [31]:
df.groupby('Category').agg(
   { "Unit_Cost":'sum',
    "List_Price":["mean","sum"],
    }
)

                       Unit_Cost    List_Price
                             sum          mean     sum
Category
Beauty & Personal Care     21441   2150.000000   32250
Electronics               256611  18530.000000  370600
Fashion                    20237   1936.666667   29050
Furniture                  94165   9920.000000  148800
Home Appliances           119777  11756.666667  176350
Sports & Fitness           37408   3536.666667   53050

#### Named aggregation

In [38]:
df.groupby('Category').agg(
   Avg_Cost = ("Unit_Cost","mean"),
    Avg_Price = ("List_Price","mean")
)

                            Avg_Cost     Avg_Price
Category
Beauty & Personal Care   1429.400000   2150.000000
Electronics             12830.550000  18530.000000
Fashion                  1349.133333   1936.666667
Furniture                6277.666667   9920.000000
Home Appliances          7985.133333  11756.666667
Sports & Fitness         2493.866667   3536.666667

## Crosstab

crosstab tells frequency/count

In [42]:
df.head()

,Product_ID,Product_Name,Category_ID,Category,Subcategory,Brand,Unit_Cost,List_Price
0,P0001,Samsung Galaxy A55,CAT001,Electronics,Smartphones,Samsung,19789,30400
1,P0002,OnePlus Nord CE 4,CAT001,Electronics,Smartphones,OnePlus,31755,44700
2,P0003,Apple iPhone 15,CAT001,Electronics,Smartphones,Apple,1084,1400
3,P0004,Vivo V30,CAT001,Electronics,Smartphones,Vivo,20974,28700
4,P0005,Nothing Phone 2a,CAT001,Electronics,Smartphones,Nothing,1046,1600

In [41]:
pd.crosstab(df['Category'],df['Subcategory'])

Subcategory,Accessories,Audio,Bedroom,Cleaning,Cooling,Fitness Equipment,Fitness Wear,Haircare,Kitchen,Laptops,Living Room,Men,Office,Outdoor,Personal Care,Skincare,Smartphones,Women
Category,,,,,,,,,,,,,,,,,,
Beauty & Personal Care,0,0,0,0,0,0,0,5,0,0,0,0,0,0,5,5,0,0
Electronics,5,5,0,0,0,0,0,0,0,5,0,0,0,0,0,0,5,0
Fashion,5,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,5
Furniture,0,0,5,0,0,0,0,0,0,0,5,0,5,0,0,0,0,0
Home Appliances,0,0,0,5,5,0,0,0,5,0,0,0,0,0,0,0,0,0
Sports & Fitness,0,0,0,0,0,5,5,0,0,0,0,0,0,5,0,0,0,0

In [ ]:
pd.crosstab(df['Category'],df['Subcategory'],normalize='index')
# each row sum to 100%

Subcategory,Accessories,Audio,Bedroom,Cleaning,Cooling,Fitness Equipment,Fitness Wear,Haircare,Kitchen,Laptops,Living Room,Men,Office,Outdoor,Personal Care,Skincare,Smartphones,Women
Category,,,,,,,,,,,,,,,,,,
Beauty & Personal Care,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.333333,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,0.333333,0.333333,0.00,0.000000
Electronics,0.250000,0.25,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.25,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.25,0.000000
Fashion,0.333333,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.333333,0.000000,0.000000,0.000000,0.000000,0.00,0.333333
Furniture,0.000000,0.00,0.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.333333,0.000000,0.333333,0.000000,0.000000,0.000000,0.00,0.000000
Home Appliances,0.000000,0.00,0.000000,0.333333,0.333333,0.000000,0.000000,0.000000,0.333333,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000
Sports & Fitness,0.000000,0.00,0.000000,0.000000,0.000000,0.333333,0.333333,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,0.00,0.000000

In [ ]:
pd.crosstab(df['Category'],df['Subcategory'],normalize='columns')

# each column sum to 100%

Subcategory,Accessories,Audio,Bedroom,Cleaning,Cooling,Fitness Equipment,Fitness Wear,Haircare,Kitchen,Laptops,Living Room,Men,Office,Outdoor,Personal Care,Skincare,Smartphones,Women
Category,,,,,,,,,,,,,,,,,,
Beauty & Personal Care,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
Electronics,0.5,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
Fashion,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
Furniture,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
Home Appliances,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Sports & Fitness,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [50]:
pd.crosstab(df['Category'],df['Subcategory'],margins=True)

Subcategory,Accessories,Audio,Bedroom,Cleaning,Cooling,Fitness Equipment,Fitness Wear,Haircare,Kitchen,Laptops,Living Room,Men,Office,Outdoor,Personal Care,Skincare,Smartphones,Women,All
Category,,,,,,,,,,,,,,,,,,,
Beauty & Personal Care,0,0,0,0,0,0,0,5,0,0,0,0,0,0,5,5,0,0,15
Electronics,5,5,0,0,0,0,0,0,0,5,0,0,0,0,0,0,5,0,20
Fashion,5,0,0,0,0,0,0,0,0,0,0,5,0,0,0,0,0,5,15
Furniture,0,0,5,0,0,0,0,0,0,0,5,0,5,0,0,0,0,0,15
Home Appliances,0,0,0,5,5,0,0,0,5,0,0,0,0,0,0,0,0,0,15
Sports & Fitness,0,0,0,0,0,5,5,0,0,0,0,0,0,5,0,0,0,0,15
All,10,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,95

In [52]:
pd.crosstab(df['Category'],df['Subcategory'],values=df['Unit_Cost'],aggfunc='mean')

Subcategory,Accessories,Audio,Bedroom,Cleaning,Cooling,Fitness Equipment,Fitness Wear,Haircare,Kitchen,Laptops,Living Room,Men,Office,Outdoor,Personal Care,Skincare,Smartphones,Women
Category,,,,,,,,,,,,,,,,,,
Beauty & Personal Care,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1345.0,NaN,NaN,NaN,NaN,NaN,NaN,1153.8,1789.4,NaN,NaN
Electronics,6090.4,19597.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10704.6,NaN,NaN,NaN,NaN,NaN,NaN,14929.6,NaN
Fashion,573.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2256.4,NaN,NaN,NaN,NaN,NaN,1217.2
Furniture,NaN,NaN,7085.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9099.6,NaN,2648.4,NaN,NaN,NaN,NaN,NaN
Home Appliances,NaN,NaN,NaN,6379.0,7455.2,NaN,NaN,NaN,10121.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sports & Fitness,NaN,NaN,NaN,NaN,NaN,1778.2,3645.0,NaN,NaN,NaN,NaN,NaN,NaN,2058.4,NaN,NaN,NaN,NaN

## pivot table

it is like excel pivot table

In [61]:
pd.pivot_table(
    df,
    index = "Subcategory",
    columns = "Category",
    values=['Unit_Cost','List_Price'],
    fill_value=0,
    aggfunc=["sum",'mean']
)

                                     sum                                \
                              List_Price
Category          Beauty & Personal Care Electronics Fashion Furniture
Subcategory
Accessories                            0       42350    4300         0
Audio                                  0      143000       0         0
Bedroom                                0           0       0     55500
Cleaning                               0           0       0         0
Cooling                                0           0       0         0
Fitness Equipment                      0           0       0         0
Fitness Wear                           0           0       0         0
Haircare                           10150           0       0         0
Kitchen                                0           0       0         0
Laptops                                0       78450       0         0
Living Room                            0           0       0     73000
Men                                    0           0   15950         0
Office                                 0           0       0     20300
Outdoor                                0           0       0         0
Personal Care                       7800           0       0         0
Skincare                           14300           0       0         0
Smartphones                            0      106800       0         0
Women                                  0           0    8800         0

                                                                           \
                                                                Unit_Cost
Category          Home Appliances Sports & Fitness Beauty & Personal Care
Subcategory
Accessories                     0                0                      0
Audio                           0                0                      0
Bedroom                         0                0                      0
Cleaning                    47650                0                      0
Cooling                     53150                0                      0
Fitness Equipment               0            12500                      0
Fitness Wear                    0            26300                      0
Haircare                        0                0                   6725
Kitchen                     75550                0                      0
Laptops                         0                0                      0
Living Room                     0                0                      0
Men                             0                0                      0
Office                          0                0                      0
Outdoor                         0            14250                      0
Personal Care                   0                0                   5769
Skincare                        0                0                   8947
Smartphones                     0                0                      0
Women                           0                0                      0

                                                 ...       mean            \
                                                 ... List_Price
Category          Electronics Fashion Furniture  ...    Fashion Furniture
Subcategory                                      ...
Accessories             30452    2869         0  ...      860.0       0.0
Audio                   97988       0         0  ...        0.0       0.0
Bedroom                     0       0     35425  ...        0.0   11100.0
Cleaning                    0       0         0  ...        0.0       0.0
Cooling                     0       0         0  ...        0.0       0.0
Fitness Equipment           0       0         0  ...        0.0       0.0
Fitness Wear                0       0         0  ...        0.0       0.0
Haircare                    0       0         0  ...        0.0       0.0
Kitchen                     0       0         0  ...        0.0       0.0
Laptops                 53523       0         0  ...        0.0       0.0
Living Room                 0       0     45498  ...        0.0   14600.0
Men                         0   11282         0  ...     3190.0       0.0
Office                      0       0     13242  ...        0.0    4060.0
Outdoor                     0       0         0  ...        0.0       0.0
Personal Care               0       0         0  ...        0.0       0.0
Skincare                    0       0         0  ...        0.0       0.0
Smartphones             74648       0         0  ...        0.0       0.0
Women                       0    6086         0  ...     1760.0       0.0

                                                                           \
                                                                Unit_Cost
Category          Home Appliances Sports & Fitness Beauty & Personal Care
Subcategory
Accessories                   0.0              0.0                    0.0
Audio                         0.0              0.0                    0.0
Bedroom                       0.0              0.0                    0.0
Cleaning                   9530.0              0.0                    0.0
Cooling                   10630.0              0.0                    0.0
Fitness Equipment             0.0           2500.0                    0.0
Fitness Wear                  0.0           5260.0                    0.0
Haircare                      0.0              0.0                 1345.0
Kitchen                   15110.0              0.0                    0.0
Laptops                       0.0              0.0                    0.0
Living Room                   0.0              0.0                    0.0
Men                           0.0              0.0                    0.0
Office                        0.0              0.0                    0.0
Outdoor                       0.0           2850.0                    0.0
Personal Care                 0.0              0.0                 1153.8
Skincare                      0.0              0.0                 1789.4
Smartphones                   0.0              0.0                    0.0
Women                         0.0              0.0                    0.0

                                                                 \

Category          Electronics Fashion Furniture Home Appliances
Subcategory
Accessories            6090.4   573.8       0.0             0.0
Audio                 19597.6     0.0       0.0             0.0
Bedroom                   0.0     0.0    7085.0             0.0
Cleaning                  0.0     0.0       0.0          6379.0
Cooling                   0.0     0.0       0.0          7455.2
Fitness Equipment         0.0     0.0       0.0             0.0
Fitness Wear              0.0     0.0       0.0             0.0
Haircare                  0.0     0.0       0.0             0.0
Kitchen                   0.0     0.0       0.0         10121.2
Laptops               10704.6     0.0       0.0             0.0
Living Room               0.0     0.0    9099.6             0.0
Men                       0.0  2256.4       0.0             0.0
Office                    0.0     0.0    2648.4             0.0
Outdoor                   0.0     0.0       0.0             0.0
Personal Care             0.0     0.0       0.0             0.0
Skincare                  0.0     0.0       0.0             0.0
Smartphones           14929.6     0.0       0.0             0.0
Women                     0.0  1217.2       0.0             0.0



Category          Sports & Fitness
Subcategory
Accessories                    0.0
Audio                          0.0
Bedroom                        0.0
Cleaning                       0.0
Cooling                        0.0
Fitness Equipment           1778.2
Fitness Wear                3645.0
Haircare                       0.0
Kitchen                        0.0
Laptops                        0.0
Living Room                    0.0
Men                            0.0
Office                         0.0
Outdoor                     2058.4
Personal Care                  0.0
Skincare                       0.0
Smartphones                    0.0
Women                          0.0

[18 rows x 24 columns]

## cut()

In [62]:
df['Unit_Cost'].min()

np.int64(135)

In [63]:
df['Unit_Cost'].max()

np.int64(56203)

In [68]:
df['Unit_Cost_Group']=pd.cut(df['Unit_Cost'],bins=[100,1000,10000,20000,30000,40000,50000,60000],
labels=["100-1k","1k-10k","10k-20k","20k-30k","30k-40k","40k-50K",">50k"])

In [69]:
df.head(20)

,Product_ID,Product_Name,Category_ID,Category,Subcategory,Brand,Unit_Cost,List_Price,Unit_Cost_Group
0,P0001,Samsung Galaxy A55,CAT001,Electronics,Smartphones,Samsung,19789,30400,10k-20k
1,P0002,OnePlus Nord CE 4,CAT001,Electronics,Smartphones,OnePlus,31755,44700,30k-40k
2,P0003,Apple iPhone 15,CAT001,Electronics,Smartphones,Apple,1084,1400,1k-10k
3,P0004,Vivo V30,CAT001,Electronics,Smartphones,Vivo,20974,28700,20k-30k
4,P0005,Nothing Phone 2a,CAT001,Electronics,Smartphones,Nothing,1046,1600,1k-10k
5,P0006,HP Pavilion 14,CAT002,Electronics,Laptops,HP,3701,4850,1k-10k
6,P0007,Dell Inspiron 15,CAT002,Electronics,Laptops,Dell,12456,16850,10k-20k
7,P0008,Lenovo IdeaPad Slim 5,CAT002,Electronics,Laptops,Lenovo,4065,6750,1k-10k
8,P0009,ASUS Vivobook 15,CAT002,Electronics,Laptops,ASUS,6324,11200,1k-10k
9,P0010,Acer Aspire 5,CAT002,Electronics,Laptops,Acer,26977,38800,20k-30k
10,P0011,Sony WH-1000XM5,CAT003,Electronics,Audio,Sony,17873,28300,10k-20k
11,P0012,JBL Tune 770NC,CAT003,Electronics,Audio,JBL,56203,74400,>50k
12,P0013,Boat Airdopes 141,CAT003,Electronics,Audio,Boat,18438,31000,10k-20k
13,P0014,Bose QuietComfort,CAT003,Electronics,Audio,Bose,4201,7500,1k-10k
14,P0015,JBL Flip 6,CAT003,Electronics,Audio,JBL,1273,1800,1k-10k
15,P0016,Anker USB-C Hub,CAT013,Electronics,Accessories,Anker,20549,26600,20k-30k
16,P0017,Logitech MX Master 3S,CAT013,Electronics,Accessories,Logitech,2509,3950,1k-10k
17,P0018,Samsung 256GB SSD,CAT013,Electronics,Accessories,Samsung,4511,7600,1k-10k
18,P0019,Belkin Power Bank,CAT013,Electronics,Accessories,Belkin,1088,1650,1k-10k
19,P0020,Portronics Keyboard,CAT013,Electronics,Accessories,Portronics,1795,2550,1k-10k