- concat()
- merge()
- join()

In [1]:
import pandas as pd

In [2]:
orders = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Orders")
order_items = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Order_Items")
customers = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Customers")
products = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Products")
categories = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Categories")
stores = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Stores")
salepersons = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Salespersons")
returns = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Returns")
targets = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Targets")

In [3]:
orders.head()

,Order_ID,Order_Date,Customer_ID,Store_ID,Salesperson_ID,Payment_Mode,Order_Status,Shipping_Date,Delivery_Date,Sales_Channel
0,O000001,2025-10-03,C0298,S022,SP061,Credit Card,Delivered,2025-10-04,2025-10-09,Online
1,O000002,2025-12-01,C0710,S060,SP077,Credit Card,Delivered,2025-12-04,2025-12-09,In-Store
2,O000003,2025-12-07,C0333,S034,SP068,UPI,Delivered,2025-12-08,2025-12-10,In-Store
3,O000004,2025-05-31,C0737,S019,SP057,UPI,Delivered,2025-06-03,2025-06-07,Online
4,O000005,2025-05-21,C0851,S070,SP076,Debit Card,Delivered,2025-05-23,2025-05-25,Online

## concat() function

In [4]:
orders.head()

,Order_ID,Order_Date,Customer_ID,Store_ID,Salesperson_ID,Payment_Mode,Order_Status,Shipping_Date,Delivery_Date,Sales_Channel
0,O000001,2025-10-03,C0298,S022,SP061,Credit Card,Delivered,2025-10-04,2025-10-09,Online
1,O000002,2025-12-01,C0710,S060,SP077,Credit Card,Delivered,2025-12-04,2025-12-09,In-Store
2,O000003,2025-12-07,C0333,S034,SP068,UPI,Delivered,2025-12-08,2025-12-10,In-Store
3,O000004,2025-05-31,C0737,S019,SP057,UPI,Delivered,2025-06-03,2025-06-07,Online
4,O000005,2025-05-21,C0851,S070,SP076,Debit Card,Delivered,2025-05-23,2025-05-25,Online

In [5]:
orders.shape

(5000, 10)

In [6]:
df1 = pd.DataFrame(
    {"A":[3,2,5,3,9],
    "B":[5,3,6,2,0]}
)

df2 = pd.DataFrame(
    {"A":[1,2,4,3,7],
    "B":[2,3,6,2,1]}
)

In [7]:
pd.concat([df1,df2],axis=0)

   A  B
0  3  5
1  2  3
2  5  6
3  3  2
4  9  0
0  1  2
1  2  3
2  4  6
3  3  2
4  7  1

## merge() function

In [8]:
pd.merge(orders,customers,how='inner',on="Customer_ID").head()

,Order_ID,Order_Date,Customer_ID,Store_ID,Salesperson_ID,Payment_Mode,Order_Status,Shipping_Date,Delivery_Date,Sales_Channel,Customer_Name,Gender,Age,City,State,Region,Customer_Segment,Signup_Date
0,O000001,2025-10-03,C0298,S022,SP061,Credit Card,Delivered,2025-10-04,2025-10-09,Online,Vivaan Iyer,Female,34,Delhi,Delhi,North,Consumer,2024-08-15
1,O000002,2025-12-01,C0710,S060,SP077,Credit Card,Delivered,2025-12-04,2025-12-09,In-Store,Gurpreet Bansal,Male,33,Coimbatore,Tamil Nadu,South,Consumer,2023-03-12
2,O000003,2025-12-07,C0333,S034,SP068,UPI,Delivered,2025-12-08,2025-12-10,In-Store,Riya Sethi,Male,34,Chennai,Tamil Nadu,South,Small Business,2025-10-19
3,O000004,2025-05-31,C0737,S019,SP057,UPI,Delivered,2025-06-03,2025-06-07,Online,Neha Malhotra,Male,24,Coimbatore,Tamil Nadu,South,Small Business,2022-08-04
4,O000005,2025-05-21,C0851,S070,SP076,Debit Card,Delivered,2025-05-23,2025-05-25,Online,Aadhya Joshi,Male,25,Jalandhar,Punjab,North,Consumer,2023-07-04

In [9]:
pd.merge(orders,customers,how='left',on="Customer_ID").head()

,Order_ID,Order_Date,Customer_ID,Store_ID,Salesperson_ID,Payment_Mode,Order_Status,Shipping_Date,Delivery_Date,Sales_Channel,Customer_Name,Gender,Age,City,State,Region,Customer_Segment,Signup_Date
0,O000001,2025-10-03,C0298,S022,SP061,Credit Card,Delivered,2025-10-04,2025-10-09,Online,Vivaan Iyer,Female,34,Delhi,Delhi,North,Consumer,2024-08-15
1,O000002,2025-12-01,C0710,S060,SP077,Credit Card,Delivered,2025-12-04,2025-12-09,In-Store,Gurpreet Bansal,Male,33,Coimbatore,Tamil Nadu,South,Consumer,2023-03-12
2,O000003,2025-12-07,C0333,S034,SP068,UPI,Delivered,2025-12-08,2025-12-10,In-Store,Riya Sethi,Male,34,Chennai,Tamil Nadu,South,Small Business,2025-10-19
3,O000004,2025-05-31,C0737,S019,SP057,UPI,Delivered,2025-06-03,2025-06-07,Online,Neha Malhotra,Male,24,Coimbatore,Tamil Nadu,South,Small Business,2022-08-04
4,O000005,2025-05-21,C0851,S070,SP076,Debit Card,Delivered,2025-05-23,2025-05-25,Online,Aadhya Joshi,Male,25,Jalandhar,Punjab,North,Consumer,2023-07-04

In [10]:
pd.merge(orders,customers,how='right',on="Customer_ID").head()

,Order_ID,Order_Date,Customer_ID,Store_ID,Salesperson_ID,Payment_Mode,Order_Status,Shipping_Date,Delivery_Date,Sales_Channel,Customer_Name,Gender,Age,City,State,Region,Customer_Segment,Signup_Date
0,O000389,2025-11-12,C0001,S026,SP006,Debit Card,Delivered,2025-11-13,2025-11-17,Online,Aarav Gupta,Female,61,Mumbai,Maharashtra,West,Corporate,2022-06-02
1,O001337,2026-05-07,C0001,S054,SP046,Net Banking,Delivered,2026-05-09,2026-05-12,Online,Aarav Gupta,Female,61,Mumbai,Maharashtra,West,Corporate,2022-06-02
2,O001416,2025-04-20,C0001,S037,SP001,UPI,Delivered,2025-04-23,2025-04-26,Phone,Aarav Gupta,Female,61,Mumbai,Maharashtra,West,Corporate,2022-06-02
3,O002890,2025-03-17,C0001,S019,SP044,Credit Card,Delivered,2025-03-20,2025-03-25,Phone,Aarav Gupta,Female,61,Mumbai,Maharashtra,West,Corporate,2022-06-02
4,O004064,2025-05-08,C0001,S047,SP046,UPI,Delivered,2025-05-10,2025-05-11,In-Store,Aarav Gupta,Female,61,Mumbai,Maharashtra,West,Corporate,2022-06-02

In [11]:
pd.merge(orders,customers,how='outer',on="Customer_ID").head()

,Order_ID,Order_Date,Customer_ID,Store_ID,Salesperson_ID,Payment_Mode,Order_Status,Shipping_Date,Delivery_Date,Sales_Channel,Customer_Name,Gender,Age,City,State,Region,Customer_Segment,Signup_Date
0,O000389,2025-11-12,C0001,S026,SP006,Debit Card,Delivered,2025-11-13,2025-11-17,Online,Aarav Gupta,Female,61,Mumbai,Maharashtra,West,Corporate,2022-06-02
1,O001337,2026-05-07,C0001,S054,SP046,Net Banking,Delivered,2026-05-09,2026-05-12,Online,Aarav Gupta,Female,61,Mumbai,Maharashtra,West,Corporate,2022-06-02
2,O001416,2025-04-20,C0001,S037,SP001,UPI,Delivered,2025-04-23,2025-04-26,Phone,Aarav Gupta,Female,61,Mumbai,Maharashtra,West,Corporate,2022-06-02
3,O002890,2025-03-17,C0001,S019,SP044,Credit Card,Delivered,2025-03-20,2025-03-25,Phone,Aarav Gupta,Female,61,Mumbai,Maharashtra,West,Corporate,2022-06-02
4,O004064,2025-05-08,C0001,S047,SP046,UPI,Delivered,2025-05-10,2025-05-11,In-Store,Aarav Gupta,Female,61,Mumbai,Maharashtra,West,Corporate,2022-06-02

In [12]:
sales = pd.DataFrame(
    {
        "Store":['Delhi','Delhi','Mumbai'],
        "Products":['Laptop','Mouse','Laptop'],
        "Sales":[50000,1000,60000]
    }
)


trgt = pd.DataFrame(
    {
        "Store":['Delhi','Delhi','Mumbai'],
        "Products":['Laptop','Mouse','Laptop'],
        'target':[55000,1200,65000]
    }
)


pd.merge(sales,trgt,on=["Store","Products"])

    Store Products  Sales  target
0   Delhi   Laptop  50000   55000
1   Delhi    Mouse   1000    1200
2  Mumbai   Laptop  60000   65000

In [13]:
sales = pd.DataFrame(
    {
        "Store":['Delhi','Delhi','Mumbai'],
        "products":['Laptop','Mouse','Laptop'],
        "Sales":[50000,1000,60000]
    }
)


trgt = pd.DataFrame(
    {
        "store":['Delhi','Delhi','Mumbai'],
        "Products":['Laptop','Mouse','Laptop'],
        'target':[55000,1200,65000]
    }
)

pd.merge(sales,trgt,left_on=["Store","products"],right_on=['store','Products'])

    Store products  Sales   store Products  target
0   Delhi   Laptop  50000   Delhi   Laptop   55000
1   Delhi    Mouse   1000   Delhi    Mouse    1200
2  Mumbai   Laptop  60000  Mumbai   Laptop   65000

In [19]:
df =pd.merge(
    pd.merge(
        pd.merge(
            pd.merge(
            pd.merge(orders,customers,on='Customer_ID',how='inner'),
            salepersons,on='Salesperson_ID',how='inner'),
                pd.merge(targets,stores,how='inner',on='Store_ID'),
                how='inner',on='Store_ID'),
                returns,on='Order_ID',how='inner'),
                pd.merge(pd.merge(order_items,products,on='Product_ID',how="inner")
                ,categories,on='Category_ID',how='inner'),how='inner',on='Order_ID')

In [20]:
df.head()

,Order_ID,Order_Date,Customer_ID,Store_ID,Salesperson_ID,Payment_Mode,Order_Status,Shipping_Date,Delivery_Date,Sales_Channel_x,...,Profit,Product_Name,Category_ID,Category_x,Subcategory_x,Brand,Unit_Cost,List_Price,Category_y,Subcategory_y
0,O000015,2025-12-22,C0901,S065,SP086,UPI,Delivered,2025-12-23,2025-12-24,In-Store,...,1896.0,Puma Sports Shoes,CAT012,Fashion,Women,Puma,3363,4700,Fashion,Women
1,O000015,2025-12-22,C0901,S065,SP086,UPI,Delivered,2025-12-23,2025-12-24,In-Store,...,2854.0,Visitor Chair,CAT010,Furniture,Office,Visitor,2908,5100,Furniture,Office
2,O000015,2025-12-22,C0901,S065,SP086,UPI,Delivered,2025-12-23,2025-12-24,In-Store,...,1896.0,Puma Sports Shoes,CAT012,Fashion,Women,Puma,3363,4700,Fashion,Women
3,O000015,2025-12-22,C0901,S065,SP086,UPI,Delivered,2025-12-23,2025-12-24,In-Store,...,2854.0,Visitor Chair,CAT010,Furniture,Office,Visitor,2908,5100,Furniture,Office
4,O000015,2025-12-22,C0901,S065,SP086,UPI,Delivered,2025-12-23,2025-12-24,In-Store,...,1896.0,Puma Sports Shoes,CAT012,Fashion,Women,Puma,3363,4700,Fashion,Women

In [15]:
df.head()

,Order_ID,Order_Date,Customer_ID,Store_ID,Salesperson_ID,Payment_Mode,Order_Status,Shipping_Date,Delivery_Date,Sales_Channel_x,...,Returned_Quantity,Return_Reason,Refund_Amount,Product_ID_y,Quantity,Unit_Price,Discount,Sales,Cost,Profit
0,O000015,2025-12-22,C0901,S065,SP086,UPI,Delivered,2025-12-23,2025-12-24,In-Store,...,3,Changed Mind,11985.0,P0059,3,4700,0.15,11985.0,10089,1896.0
1,O000015,2025-12-22,C0901,S065,SP086,UPI,Delivered,2025-12-23,2025-12-24,In-Store,...,3,Changed Mind,11985.0,P0049,2,5100,0.15,8670.0,5816,2854.0
2,O000015,2025-12-22,C0901,S065,SP086,UPI,Delivered,2025-12-23,2025-12-24,In-Store,...,3,Changed Mind,11985.0,P0059,3,4700,0.15,11985.0,10089,1896.0
3,O000015,2025-12-22,C0901,S065,SP086,UPI,Delivered,2025-12-23,2025-12-24,In-Store,...,3,Changed Mind,11985.0,P0049,2,5100,0.15,8670.0,5816,2854.0
4,O000015,2025-12-22,C0901,S065,SP086,UPI,Delivered,2025-12-23,2025-12-24,In-Store,...,3,Changed Mind,11985.0,P0059,3,4700,0.15,11985.0,10089,1896.0

In [21]:
df.shape

(17840, 55)

In [22]:
df.to_csv("merged_table.csv",index=False)