In [1]:
import pandas as pd

In [2]:
orders = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Orders")
order_items = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Order_Items")
customers = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Customers")
products = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Products")
categories = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Categories")
stores = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Stores")
salepersons = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Salespersons")
returns = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Returns")
targets = pd.read_excel("Indian_Sales_Dataset.xlsx",sheet_name="Targets")

## Join

Join combines the dataframe based on their index.

In [3]:
df1 = pd.DataFrame(
    {
        "Name":["Amit","Riya","Rahul"],
        "Department":["IT","HR","Finance"],
    },index=[101,102,103]
)

In [5]:
df2 = pd.DataFrame(
    {
        "Salary":[50000,60000,45000]
    },index = [101,102,104]
)

In [6]:
df1.join(df2)

      Name Department   Salary
101   Amit         IT  50000.0
102   Riya         HR  60000.0
103  Rahul    Finance      NaN

In [7]:
df1.join(df2,how='left')

      Name Department   Salary
101   Amit         IT  50000.0
102   Riya         HR  60000.0
103  Rahul    Finance      NaN

In [8]:
df1.join(df2,how='right')

     Name Department  Salary
101  Amit         IT   50000
102  Riya         HR   60000
104   NaN        NaN   45000

In [9]:
df1.join(df2,how='inner')

     Name Department  Salary
101  Amit         IT   50000
102  Riya         HR   60000

In [10]:
df1.join(df2,how='outer')

      Name Department   Salary
101   Amit         IT  50000.0
102   Riya         HR  60000.0
103  Rahul    Finance      NaN
104    NaN        NaN  45000.0

In [11]:
df3 = pd.DataFrame(
    {   "EmpID":[101,102,103],
        "Name":["Amit","Riya","Rahul"],
        "Department":["IT","HR","Finance"],
    }
)

In [13]:
df2

     Salary
101   50000
102   60000
104   45000

In [12]:
df3

   EmpID   Name Department
0    101   Amit         IT
1    102   Riya         HR
2    103  Rahul    Finance

In [16]:
df3.join(df2,on='EmpID')

   EmpID   Name Department   Salary
0    101   Amit         IT  50000.0
1    102   Riya         HR  60000.0
2    103  Rahul    Finance      NaN

### Difference between join() and merge()

|Feature | join() | merge() |
|--------|-------|--------|
|Default matching key | index | common columns, when available |
|Column based joining | supported with on parameter | directly supported with on |
|Best Suited for | Joining  data frames based on index | Joining tables using key columns|